CREATE OR REPLACE PROCEDURE STDDEV (OUT STDDEV DECIMAL(16,4))
LANGUAGE SQL
P1: BEGIN
        DECLARE SQLSTATE CHAR(5) DEFAULT '00000';
        DECLARE NUM_ROWS INT;
        DECLARE SUM_SALARY DECIMAL(16,4);
        DECLARE SUM_SALARY_SQUARED DECIMAL(16,4);
        DECLARE TEMP DECIMAL(16,4);
        DECLARE AVG_SALARY DECIMAL(16,4);
        DECLARE AVG_SALARY_SQUARED DECIMAL(16,4);
        DECLARE cursor1 CURSOR FOR SELECT SALARY FROM EMPLOYEE;

        SET SUM_SALARY = 0;
        SET SUM_SALARY_SQUARED = 0;
        SET NUM_ROWS = 0;
        SET TEMP = 0;

        OPEN cursor1;
        FETCH FROM cursor1 INTO TEMP;
        WHILE(SQLSTATE = '00000')
        DO
            SET SUM_SALARY = SUM_SALARY + TEMP;
            SET SUM_SALARY_SQUARED = SUM_SALARY_SQUARED + (TEMP * TEMP);
            SET NUM_ROWS = NUM_ROWS + 1;
            FETCH FROM cursor1 INTO TEMP;
        END WHILE;
        CLOSE cursor1;
        SET AVG_SALARY = SUM_SALARY/CAST(NUM_ROWS AS DECIMAL(16,4));
        SET AVG_SALARY_SQUARED = SUM_SALARY_SQUARED/CAST(NUM_ROWS AS DECIMAL(16,4));
        SET STDDEV = SQRT(AVG_SALARY_SQUARED - (AVG_SALARY * AVG_SALARY));      
END P1@
CALL STDDEV(?);@