CONNECT TO SAMPLE;
WITH MONTHLY_SALES(YEARMONTH,MONTHLY_DOSAGE_UNIT) AS (SELECT YEAR(TRANSACTION_DATE) || 
CASE 
    WHEN (CAST( MONTH(TRANSACTION_DATE) AS INT)  < 10 ) 
         THEN '0' || CAST( MONTH(TRANSACTION_DATE) AS INT)
    ELSE CAST ( MONTH(TRANSACTION_DATE) AS CHAR(2))
END AS TRANSACTION_YEAR_AND_MONTH, SUM(DOSAGE_UNIT) FROM CSE532.DEA_NY GROUP BY YEAR(TRANSACTION_DATE),MONTH(TRANSACTION_DATE))
SELECT YEARMONTH, MONTHLY_DOSAGE_UNIT, avg(MONTHLY_DOSAGE_UNIT) OVER (ORDER BY YEARMONTH ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS SMOOTHED_MONTHLY_DOSAGE_UNIT FROM MONTHLY_SALES;